version: 2

sources:
  - name: dev
    tables:
      - name: predictions
  - name: nasdaq
    tables:
      - name: listed_stocks
  - name: td
    tables:
      - name: equities_raw
      - name: options_raw
      - name: quotes_raw
