# Light weight jupyter notebook for non-gpu data exploration
FROM python:3

# Install miniconda
RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# Create py env
RUN /home/user/miniconda/bin/conda install conda-build \
 && /home/user/miniconda/bin/conda create -y --name py36 python=3.6.5 \
 && /home/user/miniconda/bin/conda clean -ya
ENV CONDA_DEFAULT_ENV=py36
ENV CONDA_PREFIX=/home/user/miniconda/envs/$CONDA_DEFAULT_ENV
ENV PATH=$CONDA_PREFIX/bin:$PATH

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN conda install -c conda-forge jupyterlab

RUN conda install graphviz

ENV PYTHONPATH=$PYTHONPATH:/usr/src/app

WORKDIR /usr/src/app

CMD ["python"]
