QUERY = """
    CREATE TABLE IF NOT EXISTS td.options (
        symbol                      text,
        volatility                  numeric(20,6),
        n_contracts                 numeric(20,6),
        interest_rate               numeric(20,6),
        put_call                    text,
        description                 text,
        exchange_name               text,
        bid                         numeric(20,6),
        ask                         numeric(20,6),
        last                        numeric(20,6),
        mark                        numeric(20,6),
        bid_size                    numeric(20,6),
        ask_size                    numeric(20,6),
        bid_ask_size                text,
        last_size                   numeric(20,6),
        high_price                  numeric(20,6),
        low_price                   numeric(20,6),
        open_price                  numeric(20,6),
        close_price                 numeric(20,6),
        total_volume                numeric(20,6),
        trade_date                  timestamp without time zone,
        trade_time_in_long          text,
        quote_time_in_long          text,
        net_change                  numeric(20,6),
        delta                       numeric(60,20),
        gamma                       numeric(60,20),
        theta                       numeric(60,20),
        vega                        numeric(60,20),
        rho                         numeric(60,20),
        open_interest               numeric(20,6),
        time_value                  numeric(20,6),
        theoretical_option_value    numeric(20,6),
        theoretical_volatility      numeric(20,6),
        option_deliverable_list     text,
        strike_price                numeric(20,6),
        expiration_date             text,
        days_to_expiration          numeric(20,6),
        expiration_type             text,
        last_trading_day            text,
        multiplier                  numeric(20,6),
        settlement_type             text,
        deliverable_note            text,
        is_index_option             text,
        percent_change              numeric(20,6),
        mark_change                 numeric(20,6),
        mark_percent_change         numeric(20,6),
        non_standard                text,
        mini                        text,
        in_the_money                text,
        expiration_date_from_epoch  timestamp without time zone,
        strike                      numeric(20,6),
        strike_date                 timestamp without time zone,
        days_to_expiration_date     numeric(20,6),
        dw_created_at               timestamp without time zone
    );
    """